name: Run Tests

on: [push]

jobs:
  test:
    name: Run tests on ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run tests
      run: |
        npm ci
        npm test
      env:
        CI: true
        NODE_ENV: ci
